dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk8

# Nashorn is only supported in 1.8
#  - oraclejdk7
#  - openjdk7

# Get the latest JDK, otherwise might use slightly older version
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_script:
  - cd $TRAVIS_BUILD_DIR/lib
  - wget https://www.dropbox.com/s/6vsztd0u87bm7sd/Spigot.jar
  - cd $TRAVIS_BUILD_DIR
after_success:
  - echo "No logs to display from folder $TRAVIS_BUILD_DIR/target/"
after_failure:
  - cat $TRAVIS_BUILD_DIR/target/*.log
